### ISSUE TITLE
question about kinect2.yaml 

### ISSUE THREAD

**Issue by JeonHyeongJunKW** [EXing/ORB_SLAM2#1]
Hello. I'm going to use the Kinect2 model, too. I think the calibration parameter of kinect2.yaml in your Example/kinect2 is different from DRE SLAM, is there a reason?

I would like to use the kinect 2 model of SLAM below.
[DRE SLAM](https://github.com/ydsf16/dre_slam/blob/master/config/comparative_test.yaml)

**Comment by EXing** [comment]
calibrated by iai_kinect
